library(lubridate)
ucidata <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
ucidata$Date <- dmy(ucidata$Date)
testg <- grep("2007-02-01|2007-02-02", ucidata$Date, value = FALSE)
w_ds <- ucidata[testg,]
rm(ucidata)
rm(testg)
w_ds$combinedDT <- paste(w_ds$Date, w_ds$Time, sep = " ")
w_ds$combinedDT <- ymd_hms(w_ds$combinedDT)
png(file = "plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
with(w_ds, {
  plot(combinedDT, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
  plot(combinedDT, Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
  mtext("datetime", side = 1, outer = TRUE)
  plot(combinedDT, Sub_metering_1,type = "l",xlab = "", ylab = "Energy sub metering")
  lines(combinedDT,Sub_metering_2, col = "red")
  lines(combinedDT,Sub_metering_3, col = "blue")
  legend("topright", lty = "solid", bty = "n", col = c("black", "red", "blue"), cex = .95, xjust = 1,x.intersp = 1.2,legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  plot(combinedDT, Global_reactive_power, type = "l", xlab = "datetime")
  mtext("datetime", side = 1, outer = TRUE)
})
dev.off()