library(lubridate)
ucidata <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
ucidata$Date <- dmy(ucidata$Date)
testg <- grep("2007-02-01|2007-02-02", ucidata$Date, value = FALSE)
w_ds <- ucidata[testg,]
rm(ucidata)
rm(testg)
w_ds$combinedDT <- paste(w_ds$Date, w_ds$Time, sep = " ")
w_ds$combinedDT <- ymd_hms(w_ds$combinedDT)
png(file = "plot3.png", width = 480, height = 480)
with(w_ds,plot(combinedDT, Sub_metering_1,type = "l",xlab = "", ylab = "Energy sub metering"))
with(w_ds,lines(combinedDT,Sub_metering_2, col = "red"))
with(w_ds,lines(combinedDT,Sub_metering_3, col = "blue"))
legend("topright", lty = "solid", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()